import os

from ACME import ACME
from celery import Celery
from email_utils import send_email

rdip = os.environ["REDIS_HOST"]
cont_host = os.environ["CONT_HOST"]
celery = Celery("tasks", broker=f"redis://{rdip}:6379/0")


@celery.task
def process_data_task(email, uuid_value, opeanapi, output_dir, vdata):
    acme = ACME(output_dir)
    print("=========================== In TASK  ===============================")
    print(vdata)
    acme.acmeEntry(uuid_value, opeanapi, output_dir, vdata)
    subject = "Your ACME-Generated Postman Test Files Are Ready for Download"
    web_server = f"http://{cont_host}:5000"
    email_body = f"""Dear Customer,

    Your Postman vulnerability assessment test cases, generated by the ACME system, are now available for download.

    Test Cases Download:
    {web_server}/pm/{uuid_value}
    
    To download the corresponding environment file, including parameter placeholders, please use the link below:

    Environment Variables File Download:
    {web_server}/ev/{uuid_value}

    Please note that environment variables values are left blank. Kindly review and update them according to your specific configuration before running the test collection.

    Best regards,
    ACME Automated Delivery System"""

    send_email(email, subject, email_body)
